apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: dev
    server: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-project
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: prod
    server: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-project
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: test
    server: '*'
